#This is an example template used to generate a file

src_file: "template_terrain_fixed.xml"  # This is the NAME of the template file we build upon.
terrain_file: "fixed_terrain.xml"  # This is the name of our created terrain. It gets saved.

paths:
  template_dir: "../template_terrains"
  saved_dir: "../saved_terrains"

parameters:
  n: 500  # Number of rocks to make
  size_range: [0.005, 0.015]  # Size
  scatter_range: [-0.5, 0.5]  # Grid area over which the rocks are scattered
  height_range: [0, 0.015]  # Heights at which the rocks are placed
  quat_range: [0, 1]  # Rotation angles of the rocks
  rock_type: "ellipsoid"  # Type of rock shape
